MobileOrder/Models/Business.cs
using System;
using System.Collections.Generic;

namespace MobileOrder.Models  
{                                                                                                   
    public partial class Business   
    {
        public int Id { get; set; }
        public string BusinessName { get; set; }
        public Nullable<int> FranchiseId { get; set; }
        public virtual Franchise Franchise { get; set; }
    }
    public class BusinessList : List<Business  > 
    {
        public BusinessList() { }
        public BusinessList(IEnumerable<Business  > items) : base(items) { }
    }
}

MobileOrder/Models/Condiment.cs
using System;
using System.Collections.Generic;

namespace MobileOrder.Models  
{                                                                                                   
    public partial class Condiment   
    {
        public Condiment()
        {
            this.Condiment1 = new CondimentList();
            this.OrderLineItems = new OrderLineItemList();
        }

        public int Id { get; set; }
        public string CondimentName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string SubCategory { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public bool StartChecked { get; set; }
        public int FoodItemId { get; set; }
        public Nullable<int> CondimentId { get; set; }
        public virtual CondimentList Condiment1 { get; set; }
        public virtual Condiment Condiment2 { get; set; }
        public virtual FoodItem FoodItem { get; set; }
        public virtual OrderLineItemList OrderLineItems { get; set; }
    }
    public class CondimentList : List<Condiment  > 
    {
        public CondimentList() { }
        public CondimentList(IEnumerable<Condiment  > items) : base(items) { }
    }
}

MobileOrder/Controllers/CondimentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MobileOrder.Models;
using MobileOrder.Services; 
using MobileOrder.ViewModels; 

namespace MobileOrder.Controllers
{
    public class CondimentController : Controller
    {
        public CondimentController(CondimentSvc condimentSvc)

        {
            _condimentSvc = condimentSvc;
        }
        private CondimentSvc _condimentSvc;


        //
        // GET: /Condiment/

        public ActionResult Index()
        {
            return View(new CondimentList(_condimentSvc.GetAll()));
        }

        //
        // GET: /Condiment/Details/5

        public ActionResult Details(int id = 0)
        {
            Condiment condiment = _condimentSvc.GetById(id);
            if (condiment == null)
            {
                return HttpNotFound();
            }
            CondimentVm condimentVm = new CondimentVm(condiment);





            return View(condimentVm);
        }

        //
        // GET: /Condiment/Create

        public ActionResult Create(
            int? FoodItemId        )
        {
                Condiment condiment = new Condiment();
                if (FoodItemId.HasValue)
               {
                    condiment.FoodItemId = FoodItemId.Value;
               }
CondimentVm condimentVm = new CondimentVm(condiment);
            return View(condimentVm);
        }

        //
        // POST: /Condiment/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CondimentVm condimentVm)
        {
#if(DEBUG)
             var errors = ModelState
            .Where(x => x.Value.Errors.Count > 0)
            .Select(x => new { x.Key, x.Value.Errors })
            .ToArray();
#endif
            if (ModelState.IsValid)
            {
                _condimentSvc.Update(condimentVm.Condiment);
                return RedirectToAction("Index");
            }

            return View(condimentVm);
        }

        //
        // GET: /Condiment/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Condiment condiment = _condimentSvc.GetById(id);
            if (condiment == null)
            {
                return HttpNotFound();
            }
            CondimentVm condimentVm = new CondimentVm(condiment);
            return View(condimentVm);
        }

        //
        // POST: /Condiment/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CondimentVm condimentVm)
        {
            if (ModelState.IsValid)
            {
                _condimentSvc.Update(condimentVm.Condiment);
                return RedirectToAction("Index");
            }
            return View(condimentVm);
        }

        //
        // GET: /Condiment/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Condiment condiment = _condimentSvc.GetById(id);
            if (condiment == null)
            {
                return HttpNotFound();
            }
            CondimentVm condimentVm = new CondimentVm(condiment);
            return View(condimentVm);
        }

        //
        // POST: /Condiment/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            _condimentSvc.Delete(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }
    }
}

MobileOrder/Controllers/CustomerOrderController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MobileOrder.Models;
using MobileOrder.Services; 
using MobileOrder.ViewModels; 

namespace MobileOrder.Controllers
{
    public class CustomerOrderController : Controller
    {
        public CustomerOrderController(CustomerOrderSvc customerOrderSvc)

        {
            _customerOrderSvc = customerOrderSvc;
        }
        private CustomerOrderSvc _customerOrderSvc;


        //
        // GET: /CustomerOrder/

        public ActionResult Index()
        {
            return View(new CustomerOrderList(_customerOrderSvc.GetAll()));
        }

        //
        // GET: /CustomerOrder/Details/5

        public ActionResult Details(int id = 0)
        {
            CustomerOrder customerOrder = _customerOrderSvc.GetById(id);
            if (customerOrder == null)
            {
                return HttpNotFound();
            }
            CustomerOrderVm customerOrderVm = new CustomerOrderVm(customerOrder);





            return View(customerOrderVm);
        }

        //
        // GET: /CustomerOrder/Create

        public ActionResult Create(
            int? CustomerId,            int? LocationId        )
        {
                CustomerOrder customerOrder = new CustomerOrder();
                if (CustomerId.HasValue)
               {
                    customerOrder.CustomerId = CustomerId.Value;
               }
                if (LocationId.HasValue)
               {
                    customerOrder.LocationId = LocationId.Value;
               }
CustomerOrderVm customerOrderVm = new CustomerOrderVm(customerOrder);
            return View(customerOrderVm);
        }

        //
        // POST: /CustomerOrder/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CustomerOrderVm customerOrderVm)
        {
#if(DEBUG)
             var errors = ModelState
            .Where(x => x.Value.Errors.Count > 0)
            .Select(x => new { x.Key, x.Value.Errors })
            .ToArray();
#endif
            if (ModelState.IsValid)
            {
                _customerOrderSvc.Update(customerOrderVm.CustomerOrder);
                return RedirectToAction("Index");
            }

            return View(customerOrderVm);
        }

        //
        // GET: /CustomerOrder/Edit/5

        public ActionResult Edit(int id = 0)
        {
            CustomerOrder customerOrder = _customerOrderSvc.GetById(id);
            if (customerOrder == null)
            {
                return HttpNotFound();
            }
            CustomerOrderVm customerOrderVm = new CustomerOrderVm(customerOrder);
            return View(customerOrderVm);
        }

        //
        // POST: /CustomerOrder/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CustomerOrderVm customerOrderVm)
        {
            if (ModelState.IsValid)
            {
                _customerOrderSvc.Update(customerOrderVm.CustomerOrder);
                return RedirectToAction("Index");
            }
            return View(customerOrderVm);
        }

        //
        // GET: /CustomerOrder/Delete/5

        public ActionResult Delete(int id = 0)
        {
            CustomerOrder customerOrder = _customerOrderSvc.GetById(id);
            if (customerOrder == null)
            {
                return HttpNotFound();
            }
            CustomerOrderVm customerOrderVm = new CustomerOrderVm(customerOrder);
            return View(customerOrderVm);
        }

        //
        // POST: /CustomerOrder/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            _customerOrderSvc.Delete(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }
    }
}

MobileOrder/Controllers/FranchiseController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MobileOrder.Models;
using MobileOrder.Services; 
using MobileOrder.ViewModels; 

namespace MobileOrder.Controllers
{
    public class FranchiseController : Controller
    {
        public FranchiseController(FranchiseSvc franchiseSvc)

        {
            _franchiseSvc = franchiseSvc;
        }
        private FranchiseSvc _franchiseSvc;


        //
        // GET: /Franchise/

        public ActionResult Index()
        {
            return View(new FranchiseList(_franchiseSvc.GetAll()));
        }

        //
        // GET: /Franchise/Details/5

        public ActionResult Details(int id = 0)
        {
            Franchise franchise = _franchiseSvc.GetById(id);
            if (franchise == null)
            {
                return HttpNotFound();
            }
            FranchiseVm franchiseVm = new FranchiseVm(franchise);





            return View(franchiseVm);
        }

        //
        // GET: /Franchise/Create

        public ActionResult Create(
        )
        {
                Franchise franchise = new Franchise();
FranchiseVm franchiseVm = new FranchiseVm(franchise);
            return View(franchiseVm);
        }

        //
        // POST: /Franchise/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(FranchiseVm franchiseVm)
        {
#if(DEBUG)
             var errors = ModelState
            .Where(x => x.Value.Errors.Count > 0)
            .Select(x => new { x.Key, x.Value.Errors })
            .ToArray();
#endif
            if (ModelState.IsValid)
            {
                _franchiseSvc.Update(franchiseVm.Franchise);
                return RedirectToAction("Index");
            }

            return View(franchiseVm);
        }

        //
        // GET: /Franchise/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Franchise franchise = _franchiseSvc.GetById(id);
            if (franchise == null)
            {
                return HttpNotFound();
            }
            FranchiseVm franchiseVm = new FranchiseVm(franchise);
            return View(franchiseVm);
        }

        //
        // POST: /Franchise/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(FranchiseVm franchiseVm)
        {
            if (ModelState.IsValid)
            {
                _franchiseSvc.Update(franchiseVm.Franchise);
                return RedirectToAction("Index");
            }
            return View(franchiseVm);
        }

        //
        // GET: /Franchise/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Franchise franchise = _franchiseSvc.GetById(id);
            if (franchise == null)
            {
                return HttpNotFound();
            }
            FranchiseVm franchiseVm = new FranchiseVm(franchise);
            return View(franchiseVm);
        }

        //
        // POST: /Franchise/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            _franchiseSvc.Delete(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }
    }
}

MobileOrder/Controllers/OrderLineItemController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MobileOrder.Models;
using MobileOrder.Services; 
using MobileOrder.ViewModels; 

namespace MobileOrder.Controllers
{
    public class OrderLineItemController : Controller
    {
        public OrderLineItemController(OrderLineItemSvc orderLineItemSvc)

        {
            _orderLineItemSvc = orderLineItemSvc;
        }
        private OrderLineItemSvc _orderLineItemSvc;


        //
        // GET: /OrderLineItem/

        public ActionResult Index()
        {
            return View(new OrderLineItemList(_orderLineItemSvc.GetAll()));
        }

        //
        // GET: /OrderLineItem/Details/5

        public ActionResult Details(int id = 0)
        {
            OrderLineItem orderLineItem = _orderLineItemSvc.GetById(id);
            if (orderLineItem == null)
            {
                return HttpNotFound();
            }
            OrderLineItemVm orderLineItemVm = new OrderLineItemVm(orderLineItem);





            return View(orderLineItemVm);
        }

        //
        // GET: /OrderLineItem/Create

        public ActionResult Create(
            int? CustomerOrderId        )
        {
                OrderLineItem orderLineItem = new OrderLineItem();
                if (CustomerOrderId.HasValue)
               {
                    orderLineItem.CustomerOrderId = CustomerOrderId.Value;
               }
OrderLineItemVm orderLineItemVm = new OrderLineItemVm(orderLineItem);
            return View(orderLineItemVm);
        }

        //
        // POST: /OrderLineItem/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(OrderLineItemVm orderLineItemVm)
        {
#if(DEBUG)
             var errors = ModelState
            .Where(x => x.Value.Errors.Count > 0)
            .Select(x => new { x.Key, x.Value.Errors })
            .ToArray();
#endif
            if (ModelState.IsValid)
            {
                _orderLineItemSvc.Update(orderLineItemVm.OrderLineItem);
                return RedirectToAction("Index");
            }

            return View(orderLineItemVm);
        }

        //
        // GET: /OrderLineItem/Edit/5

        public ActionResult Edit(int id = 0)
        {
            OrderLineItem orderLineItem = _orderLineItemSvc.GetById(id);
            if (orderLineItem == null)
            {
                return HttpNotFound();
            }
            OrderLineItemVm orderLineItemVm = new OrderLineItemVm(orderLineItem);
            return View(orderLineItemVm);
        }

        //
        // POST: /OrderLineItem/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(OrderLineItemVm orderLineItemVm)
        {
            if (ModelState.IsValid)
            {
                _orderLineItemSvc.Update(orderLineItemVm.OrderLineItem);
                return RedirectToAction("Index");
            }
            return View(orderLineItemVm);
        }

        //
        // GET: /OrderLineItem/Delete/5

        public ActionResult Delete(int id = 0)
        {
            OrderLineItem orderLineItem = _orderLineItemSvc.GetById(id);
            if (orderLineItem == null)
            {
                return HttpNotFound();
            }
            OrderLineItemVm orderLineItemVm = new OrderLineItemVm(orderLineItem);
            return View(orderLineItemVm);
        }

        //
        // POST: /OrderLineItem/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            _orderLineItemSvc.Delete(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }
    }
}

MobileOrder/Views/Shared/DisplayTemplates/BusinessCheckboxList.cshtml
@model List<SelectListItem>
@for (int i = 0; i < Model.Count; i++)
{
    @Html.CheckBoxFor(model => Model[i].Selected, new { disabled = "disabled"})
    @Html.DisplayFor(model => Model[i].Text)
    @Html.HiddenFor(model => Model[i].Value)
    @Html.HiddenFor(model => Model[i].Text)
    <br />
}

MobileOrder/Views/Shared/DisplayTemplates/CondimentCheckboxList.cshtml
@model List<SelectListItem>
@for (int i = 0; i < Model.Count; i++)
{
    @Html.CheckBoxFor(model => Model[i].Selected, new { disabled = "disabled"})
    @Html.DisplayFor(model => Model[i].Text)
    @Html.HiddenFor(model => Model[i].Value)
    @Html.HiddenFor(model => Model[i].Text)
    <br />
}

MobileOrder/Views/Shared/DisplayTemplates/Customer.cshtml
@model MobileOrder.Models.Customer
    <div class="display-label">
         @Html.DisplayNameFor(model => model.FirstName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.FirstName)
    </div>
    <div class="display-label">
         @Html.DisplayNameFor(model => model.LastName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LastName)
    </div>

MobileOrder/Views/Shared/DisplayTemplates/CustomerCheckboxList.cshtml
@model List<SelectListItem>
@for (int i = 0; i < Model.Count; i++)
{
    @Html.CheckBoxFor(model => Model[i].Selected, new { disabled = "disabled"})
    @Html.DisplayFor(model => Model[i].Text)
    @Html.HiddenFor(model => Model[i].Value)
    @Html.HiddenFor(model => Model[i].Text)
    <br />
}

MobileOrder/Views/Shared/DisplayTemplates/CustomerOrder.cshtml
@model MobileOrder.Models.CustomerOrder
    <div class="display-label">
         @Html.DisplayNameFor(model => model.OrderDate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.OrderDate)
    </div>
    <div class="display-label">
         @Html.DisplayNameFor(model => model.TableInfo)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.TableInfo)
    </div>
    <div class="display-label">
         @Html.DisplayNameFor(model => model.CardName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CardName)
    </div>
    <div class="display-label">
         @Html.DisplayNameFor(model => model.CardType)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CardType)
    </div>
    <div class="display-label">
         @Html.DisplayNameFor(model => model.AuthCode)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.AuthCode)
    </div>
    <div class="display-label">
         @Html.DisplayNameFor(model => model.ExpirationMonth)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ExpirationMonth)
    </div>
    <div class="display-label">
         @Html.DisplayNameFor(model => model.ExpirationYear)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ExpirationYear)
    </div>
    <div class="display-label">
         @Html.DisplayNameFor(model => model.SubTotal)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.SubTotal)
    </div>
    <div class="display-label">
         @Html.DisplayNameFor(model => model.Tax)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Tax)
    </div>
    <div class="display-label">
         @Html.DisplayNameFor(model => model.Total)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Total)
    </div>

MobileOrder/Views/Shared/DisplayTemplates/CustomerOrderList.cshtml
@model MobileOrder.Models.CustomerOrderList
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().OrderDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().TableInfo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().CardName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().CardType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().AuthCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().ExpirationMonth)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().ExpirationYear)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().SubTotal)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Tax)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Total)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.OrderDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TableInfo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CardName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CardType)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AuthCode)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ExpirationMonth)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ExpirationYear)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SubTotal)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Tax)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Total)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", "CustomerOrder", new { id = item.Id }, new { }) |
            @Html.ActionLink("Details", "Details", "CustomerOrder", new { id = item.Id }, new { }) |
            @Html.ActionLink("Delete", "Delete", "CustomerOrder", new { id = item.Id }, new { })
        </td>
    </tr>
}

</table>

MobileOrder/Views/Shared/DisplayTemplates/FoodItem.cshtml
@model MobileOrder.Models.FoodItem
    <div class="display-label">
         @Html.DisplayNameFor(model => model.FoodItemName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.FoodItemName)
    </div>
    <div class="display-label">
         @Html.DisplayNameFor(model => model.Price)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Price)
    </div>
    <div class="display-label">
         @Html.DisplayNameFor(model => model.SubCategory)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.SubCategory)
    </div>

MobileOrder/Views/Shared/DisplayTemplates/FoodItemCheckboxList.cshtml
@model List<SelectListItem>
@for (int i = 0; i < Model.Count; i++)
{
    @Html.CheckBoxFor(model => Model[i].Selected, new { disabled = "disabled"})
    @Html.DisplayFor(model => Model[i].Text)
    @Html.HiddenFor(model => Model[i].Value)
    @Html.HiddenFor(model => Model[i].Text)
    <br />
}

MobileOrder/Views/Shared/DisplayTemplates/FoodMenu.cshtml
@model MobileOrder.Models.FoodMenu
    <div class="display-label">
         @Html.DisplayNameFor(model => model.MenuName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.MenuName)
    </div>
    <div class="display-label">
         @Html.DisplayNameFor(model => model.Category)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Category)
    </div>
    <div class="display-label">
         @Html.DisplayNameFor(model => model.SubCategory)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.SubCategory)
    </div>
    <div class="display-label">
         @Html.DisplayNameFor(model => model.SortOrder)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.SortOrder)
    </div>

MobileOrder/Views/Shared/DisplayTemplates/FranchiseList.cshtml
@model MobileOrder.Models.FranchiseList
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().FranchiseName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FranchiseName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", "Franchise", new { id = item.Id }, new { }) |
            @Html.ActionLink("Details", "Details", "Franchise", new { id = item.Id }, new { }) |
            @Html.ActionLink("Delete", "Delete", "Franchise", new { id = item.Id }, new { })
        </td>
    </tr>
}

</table>

MobileOrder/Views/Shared/DisplayTemplates/LocationCheckboxList.cshtml
@model List<SelectListItem>
@for (int i = 0; i < Model.Count; i++)
{
    @Html.CheckBoxFor(model => Model[i].Selected, new { disabled = "disabled"})
    @Html.DisplayFor(model => Model[i].Text)
    @Html.HiddenFor(model => Model[i].Value)
    @Html.HiddenFor(model => Model[i].Text)
    <br />
}

MobileOrder/Views/Shared/DisplayTemplates/OrderLineItemList.cshtml
@model MobileOrder.Models.OrderLineItemList
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().ItemName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().ItemType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Quantity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().SortOrder)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ItemName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ItemType)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Quantity)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SortOrder)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", "OrderLineItem", new { id = item.Id }, new { }) |
            @Html.ActionLink("Details", "Details", "OrderLineItem", new { id = item.Id }, new { }) |
            @Html.ActionLink("Delete", "Delete", "OrderLineItem", new { id = item.Id }, new { })
        </td>
    </tr>
}

</table>

MobileOrder/Views/Shared/DisplayTemplates/RatingCheckboxList.cshtml
@model List<SelectListItem>
@for (int i = 0; i < Model.Count; i++)
{
    @Html.CheckBoxFor(model => Model[i].Selected, new { disabled = "disabled"})
    @Html.DisplayFor(model => Model[i].Text)
    @Html.HiddenFor(model => Model[i].Value)
    @Html.HiddenFor(model => Model[i].Text)
    <br />
}

MobileOrder/Views/Shared/DisplayTemplates/sysdiagram.cshtml
@model MobileOrder.Models.sysdiagram
    <div class="display-label">
         @Html.DisplayNameFor(model => model.name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.name)
    </div>
    <div class="display-label">
         @Html.DisplayNameFor(model => model.version)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.version)
    </div>
    <div class="display-label">
         @Html.DisplayNameFor(model => model.definition)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.definition)
    </div>